version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: bglaundry-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bglaundry_user
      POSTGRES_PASSWORD: bglaundry_password
      POSTGRES_DB: bglaundry_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
